[package]
name = "resrap-rs"
version = "0.1.2"
edition = "2024"
description = "A rule based code generator"
license = "MIT"
repository = "https://github.com/osdc/resrap-rs"
readme = "README.md"
keywords = ["parser", "graph", "prng"]
categories = ["compilers"]
